#!/bin/bash
# Nek5000 build config file
# (c) 2008,2009,2010 UCHICAGO ARGONNE, LLC

# source path 
SOURCE_ROOT="$NEK_SRC" 
SOURCE_ROOT_CORE="$SOURCE_ROOT/core"
SOURCE_ROOT_JL="$SOURCE_ROOT/jl"
SOURCE_ROOT_CMT="$SOURCE_ROOT/core/cmt"

# Fortran compiler
F77="mpif90 -fc=ifort"

# C compiler
CC="mpicc -cc=icc"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
#PPLIST="?" 

# plug-in list
PLUGIN_LIST=""


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
#IFMPI="false"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
USR="IO_tools.o chkpoint.o uparam.o statistics_2D.o statistics_3D.o statistics_2DIO.o statistics_2D_usr.o statistics_2D_debug.o time_series.o time_seriesIO.o pts_redistribute.o rt_filter.o "
#USR="foo.o"

# linking flags
#USR_LFLAGS="-L/usr/lib -lfoo"

# generic compiler flags
G="-I./inc_src" # -mcmodel=medium"

# optimization flags
OPT_FLAGS_STD="-O3 -xMIC-AVX512"
OPT_FLAGS_MAG="-O3 -xMIC-AVX512"

# enable AMG coarse grid solver (default XXT)
#IFAMG="true"
#IFAMG_DUMP="true"

# CVODE path
#CVODE_DIR=$HOME/cvode/lib
 
# MOAB/iMESH path
#MOAB_DIR="$HOME/moab"


###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
  SOURCE_ROOT_CORE="$SOURCE_ROOT/core"
  SOURCE_ROOT_JL="$SOURCE_ROOT/jl"
  SOURCE_ROOT_CMT="$SOURCE_ROOT/core/cmt"
fi
# do some checks and create makefile
source $SOURCE_ROOT_CORE/makenek.inc
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
exit 0
